<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List Products</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../../../public/style/index.css">
</head>
<body>
<div class="content">
<h1>Products</h1>

<div class="create-container">
    <a href="<?php echo $this->baseUrl('/products/add/') ?>">
        <button>Create Product</button>
    </a>
</div>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Image</th>
        <th>Name</th>
        <th>Categories</th>
        <th>Price</th>
        <th>Created</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <?php foreach ($this->products as $key => $product): ?>
    <tr>
        <td>
          <?php echo $product->pro_id?>
        </td>
        <td>
        <img src="<?php echo BASE_URL.UPLOAD_DIR.'/'.$product->pro_image?>">
        </td>
        <td>
            <a id="name" href="<?php echo $this->baseUrl('/products/show/id/' . $product->pro_id) ?>">
                <?php echo $product->pro_name ?>
            </a>
        </td>
        <td>
            <?php echo $product->cat_name?>
        </td>
        <td>
            R$ <?php echo $product->pro_price?>
        </td>
        <td>
            <?php echo $product->pro_created_at ?>
        </td>
        <td>
            <div class="action">
            <div class="container-edit">
                <a href="<?php echo $this->baseUrl('/products/edit/id/' . $product->pro_id) ?>">
                    <button>Edit</button>
                </a>
            </div>
            <div class="container-delete">
            <a href="<?php echo $this->baseUrl('/products/del/id/' . $product->pro_id) ?>">
                <button>Delete</button>
            </a>
            </div>

            </div>
        </td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>
</div>
</body>
</html>
